### PR TITLE
make library compatible with C++ linking

### PR DESCRIPTION
**Pull request by jmfriedt**
make library compatible with C++ linking as needed for GNU Radio Out of Tree module

### CODE REVIEW

**Comment by sp5wwp** [comment]
Thanks for the fix!

**Comment by lwvmobile** [comment]
Any particular reason why all the function prototypes have an individual #ifdef on them and not all of those inside the same one?

**Comment by jmfriedt** [comment]
It is the first time I link C functions to a C++ program so I was not sure if these statements were individual to each function declaration, but indeed I just tested and one global statement from the first to the last declaration in the header file is enough, no need for individual #ifdef.

**Comment by lwvmobile** [comment]
Yeah, let's go ahead and tidy that up to a single #ifdef to wrap those declarations, and then I'll merge the request.

**Comment by jmfriedt** [comment]
I have updated the repository with a single entry for all header prototypes.

**Pull request merged**
